### ISSUE TITLE
Non-functional-tests

### ISSUE THREAD

**Issue by KoDan76** [BME-MIT-IET/iet-hf-2023-spar-ql#5]
Issue készítője: Koppa Dániel

Issue feladatok: 

LoadTest: A szoftver többszöri illetve hosszú futásával kapcsolatos vizsgálat - Koppa Dániel 
UsabilitTesty: A szoftver UX-ének tesztelése mennyire ergonomikus könnyen tanulható? - Koppa Dániel 
ScalabilityTest: Skálázhatóság tesztelése - Takács Bálint

**Comment by KoDan76** [comment]
https://www.guru99.com/usability-testing-tutorial.html#example-usability-testing-test-cases
Alapján manuális UX tesztelést végzek

**Comment by KoDan76** [comment]
https://www.guru99.com/reliability-testing.html#reliability-testing-example 
Alapján a feature-ök Load tesztelése következik

**Comment by KoDan76** [comment]
Jazzer és OWAST dependency checker, dependency-k hozzáadása a projekthez.

**Comment by takjerbalint3** [comment]
Scalability Test:
Alaposabb utánajárás után azt ítéltem meg, hogy az alkalmazásunk szempontjából nem lehet általános ScalabilityTest-et véghez vinni.
Alapvetően a Scalability Test a következő adatok méréséről szól: válaszidő, teljesítmény, átadó képesség(internet). Majd ugyanezeknek az adatoknak a mérése, miután skálázzuk(fel-le) az egy időben alkalmazásunkat felhasználók számát, és az átlagos hívások számát az alkalmazásunkhoz.
Mivel az alkalmazásunk nem használ internet kapcsolatot, nincs se fájl feltöltés,se letöltés, és nem multiplayer, így a ScalabilityTest elvégzése lehetetlen/értelmetlen alkalmazásunknál.
